# Site settings
title: Pump Cottage Dorset
email: pumpcottagedorset@gmail.com
description: > # Pump Cottage Dorset.
baseurl: ""
url: "https://pumpcottagedorset.com"
s3: "https://s3.eu-west-2.amazonaws.com/jackwreid/pumpcottage"

# Build settings
markdown: kramdown
exclude: [node_modules]
