# Site settings
title: Pump Cottage Dorset
email: pumpcottagedorset@gmail.com
description: > # Pump Cottage Dorset.
baseurl: ""
url: "http://pumpcottagedorset.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
